### ISSUE TITLE
dealer gets backjack

### ISSUE THREAD

**Issue by orbitrrr** [Sublime-Lime/Blackjack#3]
hmmmmmmmmmm
![Screenshot 2022-11-17 161846](https://user-images.githubusercontent.com/111662657/202572359-7f332f74-0f5c-4a6e-9fe0-efd49406b4da.png)
![Screenshot 2022-11-17 161909](https://user-images.githubusercontent.com/111662657/202572658-3f85c3ff-5e33-43c0-84ae-751b727b6b28.png)

**Comment by Sublime-Lime** [comment]
Shut up stupid

**Comment by Sublime-Lime** [comment]
Who made a functional version of blackjack in python again??? thats right
